### ISSUE TITLE
unable to download single private track (JSONDecodeError)

### ISSUE THREAD

**Issue by klondix** [mrwnwttk/scdl#12]
```
./scdl 
Please enter a URL: https://soundcloud.com/honeytraptv/the-importance-of-self-care-9/s-n0h8v 
Traceback (most recent call last):
  File "./scdl", line 721, in <module>
    main()
  File "./scdl", line 56, in main
    downloadSingleTrack(soundcloudUrl, "", 0, 0)
  File "./scdl", line 170, in downloadSingleTrack
    downloadRegularPrivate(trackId, soundcloudUrl)
  File "./scdl", line 432, in downloadRegularPrivate
    privateMp3UrlJson = json.loads(privateMp3Url)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

- [x] running latest version

**Comment by mrwnwttk** [comment]
Updated scdl to fix the private downloads for 128kbps files. Should work now, please try and report back.
