### ISSUE TITLE
JSONDecodeError on line 355

### ISSUE THREAD

**Issue by sam-cross** [mrwnwttk/scdl#17]
Console output:

```
Traceback (most recent call last):
  File "scdl", line 742, in <module>
    main()
  File "scdl", line 49, in main
    downloadPlaylist(soundcloudUrl, 1)
  File "scdl", line 608, in downloadPlaylist
    downloadSingleTrack(permalinkUrl[index], trackName[index], hqFlag, album)
  File "scdl", line 186, in downloadSingleTrack
    description = getDescription(soundcloudUrl)
  File "scdl", line 520, in getDescription
    tags = json.loads(a)
  File "C:\Users\offic\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\offic\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\offic\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Happened after "lock da doors (samashi)" on here -> https://soundcloud.com/sewerXXXson/sets/grey (replace "XXX" with "per")

**Comment by sam-cross** [comment]
Tried downloading a second time and it worked. Something weird's going on. More error/NULL checks could be useful

**Comment by mrwnwttk** [comment]
You're using Windows. For some reason the JSON module crashes in random places when parsing large files when there are obscure Unicode characters. I have no clue why, but you're right: more checks might be needed.
