### ISSUE TITLE
problem downloading playlist

### ISSUE THREAD

**Issue by kahekahe** [mrwnwttk/scdl#6]
My setup is now working with Python 3.7.3 for single tracks. 

I can't get the playlist function to work though.

See my command (I think I'm using it correctly?) and error message below.

```
pi@rpi:~/Downloads/scdl $ sudo scdl -p -pl
Premium flag set!
Downloading a playlist!
Please enter a URL: http://soundcloud.com/factmag/sets/for-club-use-only-august-19
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0xb59c84f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-mobi.soundcloud.com', port=443): Max retries exceeded with url: /resolve?permalink_url=http://soundcloud.com/factmag/sets/for-club-use-only-august-19&client_id=FweeGBOOEOYJWLJN3oEyToGLKhmSz0I7&format=json&app_version=1520423007 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb59c84f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 545, in <module>
    main()
  File "/usr/local/bin/scdl", line 39, in main
    downloadPlaylist(soundcloudUrl, 1)
  File "/usr/local/bin/scdl", line 433, in downloadPlaylist
    playlistId = getPlaylistId(soundcloudUrl)
  File "/usr/local/bin/scdl", line 447, in getPlaylistId
    playlistIdRequest = requests.get(resolveUrl).content
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-mobi.soundcloud.com', port=443): Max retries exceeded with url: /resolve?permalink_url=http://soundcloud.com/factmag/sets/for-club-use-only-august-19&client_id=FweeGBOOEOYJWLJN3oEyToGLKhmSz0I7&format=json&app_version=1520423007 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb59c84f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by mrwnwttk** [comment]
You're using the command correctly. When downloading the exact same playlist as you (running Fedora) have no issues at all. Do single track downloads work? What's your network setup like?

**Comment by kahekahe** [comment]
Working fine with single tracks

I'm on raspberry pi `Raspbian GNU/Linux 10 (buster)`

Connected to wifi

**Comment by mrwnwttk** [comment]
Created a new branch called 111-connection-refused-fix and pushed an update. Please clone that branch and try downloading the playlist again.

**Comment by kahekahe** [comment]
Hi, I got an initial error that `NameError: name 'sleep' is not defined`

added this to the new `/usr/local/bin/scdl`

`from time import sleep`

but then still got this error:



```
pi@rpi:~/scdl $ sudo scdl -p
Premium flag set!
Please enter a URL: http://soundcloud.com/factmag/sets/for-club-use-only-august-19
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0xb599b3d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-mobi.soundcloud.com', port=443): Max retries exceeded with url: /resolve?permalink_url=https://http://soundcloud.com/factmag/sets/for-club-use-only-august-19&client_id=FweeGBOOEOYJWLJN3oEyToGLKhmSz0I7&format=json&app_version=1520423007 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb599b3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 449, in getPlaylistId
    playlistIdRequest = requests.get(resolveUrl).content
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-mobi.soundcloud.com', port=443): Max retries exceeded with url: /resolve?permalink_url=https://http://soundcloud.com/factmag/sets/for-club-use-only-august-19&client_id=FweeGBOOEOYJWLJN3oEyToGLKhmSz0I7&format=json&app_version=1520423007 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb599b3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0xb599b7b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-mobi.soundcloud.com', port=443): Max retries exceeded with url: /resolve?permalink_url=https://http://soundcloud.com/factmag/sets/for-club-use-only-august-19&client_id=FweeGBOOEOYJWLJN3oEyToGLKhmSz0I7&format=json&app_version=1520423007 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb599b7b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 550, in <module>
    main()
  File "/usr/local/bin/scdl", line 51, in main
    downloadPlaylist(soundcloudUrl, 1)
  File "/usr/local/bin/scdl", line 434, in downloadPlaylist
    playlistId = getPlaylistId(soundcloudUrl)
  File "/usr/local/bin/scdl", line 452, in getPlaylistId
    playlistIdRequest = requests.get(resolveUrl).content
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-mobi.soundcloud.com', port=443): Max retries exceeded with url: /resolve?permalink_url=https://http://soundcloud.com/factmag/sets/for-club-use-only-august-19&client_id=FweeGBOOEOYJWLJN3oEyToGLKhmSz0I7&format=json&app_version=1520423007 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb599b7b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by mrwnwttk** [comment]
It fails at the exact same moment and seemingly ignores the `except` meant for handling this exact error. 

What happens if you run the following code in a standalone python command line?
`resolveUrl = u"https://api-mobi.soundcloud.com/resolve?permalink_url=" + u"http://soundcloud.com/factmag/sets/for-club-use-only-august-19" + u"&client_id=" + u"FweeGBOOEOYJWLJN3oEyToGLKhmSz0I7" + u"&format=json&app_version=" + u"1520423007"

requests.get(resolveUrl).content
`

**Comment by kahekahe** [comment]
It gives exactly the same error

**Comment by mrwnwttk** [comment]
I'm starting to think that there's something wrong with your network. I'm willing to bet that I cannot replicate this on my Raspberry Pi. I'll try it and report back.

**Comment by kahekahe** [comment]
Ok, no worries if it is. Can't think of anything strange about network, just double checked and I don't have vpn running or anything.

I'm running on raspberry pi 4 by the way.

**Comment by mrwnwttk** [comment]
Okay, the only issue I've run into so far is the script struggling with http, which makes the request fail. If you enter the URL starting with https:// instead of http://, does that change anything?

**Comment by kahekahe** [comment]
Gives the same error with https

I checked on another pi and got the same issue

Also checked on a ubuntu machine and the standalone command  you suggested above works ok. I've not run the full script on the ubuntu machine as it's using `Python 3.5.2` and I don't want to update it on there.

**Comment by mrwnwttk** [comment]
Okay, now I'm officially out of ideas. I used a clean install of the latest Raspbian (running on a Raspberry Pi 4), ran nothing but
`sudo apt-get update`
`sudo apt-get upgrade`
`sudo apt-get install ffmpeg`
`sudo apt-get install python3-pip`
`sudo install git`
`git clone https://github.com/mrwnwttk/scdl.git`
`sudo bash ./install.sh`
`scdl -p -pl`

and it just worked. I have no clue what the issue could possibly be.

**Comment by kahekahe** [comment]
Ok, thanks for trying.

Still not sure what the issue is, but will let you know if I solve it

**Comment by FunFreshNew** [comment]
I'm having that similar issue too and I'm suspecting the address of the music as the main cause.
every time I tried to download music with an address that was containing numbers or some kind of symbols like "-" (just like the case of @kahekahe had) It can't be downloaded and the command showed me something just like @kahekahe had

**Comment by mrwnwttk** [comment]
I know it's probably irrelevant at some point, but maybe some of the stuff I added in over the past couple of weeks might have fixed it. I re-wrote a large portion of the script and managed to solve a whole bunch of issues.
